Mentor cell accessibility
SwiftIsland/island-app pull request #34
Opened 2019-06-24 19:49 UTC by SpacyRicochet

**Default text size**

![Simulator Screen Shot - iPhone 8 - 2019-06-24 at 21 48 20](https://user-images.githubusercontent.com/904596/60047381-e240c800-96c9-11e9-967d-dcd6f89a89f2.png)

**Accessibility maximum text size**

![Simulator Screen Shot - iPhone 8 - 2019-06-24 at 21 48 34](https://user-images.githubusercontent.com/904596/60047402-f08ee400-96c9-11e9-9b72-999ef73b7e66.png)

2019-06-24 20:07 UTC, ppeelen requested changes
Awesome work. Had some thoughts, and it needs to be Xcode 10 compatible unfortunately.

2019-06-24 20:07 UTC, ppeelen commented on SwiftIsland/Mentor/MentorCollectionViewCell.swift
> +
whitespace, sorry.

2019-06-24 20:07 UTC, ppeelen commented on SwiftIsland/Mentor/MentorCollectionView.swift
> +        layout.estimatedItemSize = CGSize(width: 320, height: 400) // TODO: Not sure how to get a 'one icon per row' layout.
What if we separate the calculation on lines 28-32 and reuse it using the `isAccessibilityCategory` flag? It can return a `CGSize` and we might not have to worry about setting the size here?

2019-06-24 20:07 UTC, ppeelen commented on SwiftIsland/Mentor/MentorCollectionViewCell.swift
> +  private func setupFonts() {
Should this method also be called on `prepareForReuse` in case a reused cell is pulled in without updated fonts?

2019-06-24 20:07 UTC, ppeelen commented on SwiftIsland/Base.lproj/Main.storyboard
> +        <capability name="collection view cell content view" minToolsVersion="11.0"/>
It requires Xcode 11 now, can't release with that yet :(

2019-06-24 21:21 UTC, SpacyRicochet commented on SwiftIsland/Mentor/MentorCollectionViewCell.swift
> +
I think this resolved itself.

2019-06-24 21:23 UTC, SpacyRicochet commented on SwiftIsland/Mentor/MentorCollectionViewCell.swift
> +  private func setupFonts() {
Unsure actually. Put it there as well.

2019-06-25 08:07 UTC, ppeelen commented on SwiftIsland/Helpers/CardViewController.swift
> +    guard let vc = UIStoryboard(name: "Mentor", bundle: nil).instantiateViewController(withIdentifier: "MentorCardViewController") as? MentorCardViewController else { return }
Nice idea to separate it! =)

2019-06-25 16:07 UTC, SpacyRicochet commented
I'm at the 'Oh well 🤷‍♂' stage now. This is why Dynamic Type is so hard to get right in apps.

![cells-not-resizing-correctly](https://user-images.githubusercontent.com/904596/60114387-08bb3d80-9774-11e9-9288-4a9e7e03942f.gif)

2019-06-25 19:18 UTC, SpacyRicochet commented
Final commit brings us to the following result;

**Default text style**

![Simulator Screen Shot - iPhone 5s - 2019-06-25 at 21 15 02](https://user-images.githubusercontent.com/904596/60126636-bafffe80-978e-11e9-9819-3b19eb2ac184.png)

**AXXXL text style**

![Simulator Screen Shot - iPhone 5s - 2019-06-25 at 21 15 18](https://user-images.githubusercontent.com/904596/60126658-c2bfa300-978e-11e9-9afe-3c3720cb8b16.png)

![Simulator Screen Shot - iPhone 5s - 2019-06-25 at 21 18 38](https://user-images.githubusercontent.com/904596/60126685-cfdc9200-978e-11e9-8f29-6521f1e17ab6.png)

2019-06-25 19:27 UTC, ppeelen approved these changes

2019-06-25 19:27 UTC, merged