Show user location on map
SwiftIsland/island-app pull request #60
Opened 2019-10-04 13:01 UTC by iglushchuk

#27 
I have implemented showing users location. Here a main scenarios:

1) if user is not on Texel Island, we set default region (as it did before, showing bungalows)
2) if user is on Texel Island and he is near bungalows, we set default region (as in scenario 1)
3) if user is on Texel Island, but further than default region, we calculate optimal region to show both user mark and bungalows

Also I used boolean flag to run setting region after receiving users location just for one time, so we don't update region after users location change (if needed, we can update region on every users location change). 
Text for Info.plist key is "We would like to show your location on map"

2019-10-04 13:18 UTC, funky-monkey commented
Thanks for the pull-request! 👍 
Looks good - clear code style and very readable.
One small request though - can you also write tests to cover the above stated scenarios?

Looking forward to merging this PR!

Best, 
Sidney

2019-10-04 13:39 UTC, iglushchuk commented
Not a problem, I will write some tests:)

2019-10-05 15:02 UTC, ppeelen requested changes
Great work! As @funky-monkey stated, some test would be awesome and a minor text change.

2019-10-05 15:02 UTC, ppeelen commented on SwiftIsland/Info.plist
> +	<string>We would like to show your location on map</string>
Minor grammatical error (on *the* map), but also it maybe even better to change this to ```We would like to show you your location on Texel```?

2019-10-06 12:06 UTC, ppeelen commented on SwiftIsland/Info.plist
> +	<string>We would like to show your location on map</string>
@iglushchuk this comment is still left

2019-10-06 22:32 UTC, iglushchuk commented on SwiftIsland/Info.plist
> +	<string>We would like to show your location on map</string>
I did't forget about it. I still working on test (want to cover scenarios on MapViewController). I will push tests with this text change.

2019-10-07 06:36 UTC, ppeelen commented on SwiftIsland/Info.plist
> +	<string>We would like to show your location on map</string>
Ah! Great :) Looking forward reading the test

2019-10-07 10:22 UTC, iglushchuk commented on SwiftIsland/Info.plist
> +	<string>We would like to show your location on map</string>
I pushed tests and text change) check it please when you have time

2019-10-08 14:29 UTC, SpacyRicochet commented on SwiftIsland/Info.plist
> +	<string>We would like to show you your location on Texel</string>
Maybe change this to explain slightly more?

> The Swift Island app uses your location to show you how to get to your sleeping accomodations on Texel.

2019-10-08 23:33 UTC, iglushchuk commented on SwiftIsland/Info.plist
> +	<string>We would like to show you your location on Texel</string>
fixed

2019-10-14 13:01 UTC, iglushchuk commented
Hi! I added some unit tests and change text in Info.plist, what about this pull request?

2019-10-14 13:13 UTC, ppeelen approved these changes
Nice work! Thanks a lot! 🌟🌟🌟

2019-10-14 13:13 UTC, merged